version: 2

jobs:
  build:
    docker:
      - image: circleci/node:11
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app

  unit-tests:
    docker:
      - image: circleci/node:11
    working_directory: ~/app
    steps:
      - restore_cache:
          keys: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Run tests
          command: npm run test -- --reporter mocha-junit-reporter --reporter-options mochaFile=~/reports/mocha/results.xml
      - store_test_results:
          path: ~/reports

  linting-tests:
    docker:
      - image: circleci/node:11
    working_directory: ~/app
    steps:
      - restore_cache:
          keys: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test linting
          command: |
            mkdir -p ~/reports/eslint
            npm run lint -- -f junit -o ~/reports/eslint/results.xml
      - store_test_results:
          path: ~/reports

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
      - linting_tests:
          requires:
            - build
