version: 2

jobs:
  checkout-code:
    docker:
      - image: circleci/node:11
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app

  build-app:
    docker:
      - image: circleci/node:11
    working_directory: ~/app
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app
      - persist_to_workspace:
          root: .
          paths: .

  unit-tests:
    docker:
      - image: circleci/node:11
    working_directory: ~/app
    steps:
      - run:
          name: Run tests
          command: npm run test -- --reporter mocha-junit-reporter --reporter-options mochaFile=~/reports/mocha/results.xml
      - store_test_results:
          path: ~/reports
      - attach_workspace:
          at: /app

  linting-tests:
    docker:
      - image: circleci/node:11
    working_directory: ~/app
    steps:
      - run:
          name: Test linting
          command: |
            mkdir -p ~/reports/eslint
            npm run lint -- -f junit -o ~/reports/eslint/results.xml
      - store_test_results:
          path: ~/reports
      - attach_workspace:
          at: /app

workflows:
  version: 2
  build-and-test:
    jobs:
      - checkout-code
      - build-app
      - unit-tests:
          requires:
            - build-app
      - linting-tests:
          requires:
            - build-app
