version: 2

jobs:
  build:
    docker:
      - image: circleci/node:11
    working_directory: ~/app
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/app/node_modules
      - persist_to_workspace:
          root: .
          paths: node_modules

  unit-tests:
    docker:
      - image: circleci/node:11
    working_directory: ~/app
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Run tests
          command: npm run coverage
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/coverage/lcov-report


  eslint:
    docker:
      - image: circleci/node:11
    working_directory: ~/app
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Test JavaScript linting
          command: |
            mkdir -p ~/reports/eslint
            npm run linting:eslint -- -f junit -o reports/eslint/results.xml
      - store_test_results:
          path: ~/reports

  stylelint:
    docker:
      - image: circleci/node:11
    working_directory: ~/app
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Test SCSS linting
          command: npm run linting:stylelint

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
      - eslint:
          requires:
            - build
      - stylelint:
          requires:
            - build
