version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          when: always
          command: npm run test -- --reporter mocha-junit-reporter --reporter-options mochaFile=~/reports/mocha/results.xml
      - run:
          name: Test linting
          when: always
          command: |
            mkdir -p ~/reports/eslint
            npm run lint -- -f junit -o ~/reports/eslint/results.xml
      - store_test_results:
          path: ~/reports
