version: 2

jobs:
  build:
    docker:
      - image: circleci/node:11
    working_directory: ~/app
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build assets
          command: npm run assets:build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ~/app/node_modules
      - persist_to_workspace:
          root: .
          paths: node_modules
  unit-tests:
    docker:
      - image: circleci/node:11
    working_directory: ~/app
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Run tests
          command: npm run test:coverage
      - store_test_results:
          path: reports
      - store_artifacts:
          path: coverage/lcov-report
  eslint:
    docker:
      - image: circleci/node:11
    working_directory: ~/app
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Test JavaScript linting
          command: |
            mkdir -p reports/eslint
            npm run eslint:report
      - store_test_results:
          path: reports
  stylelint:
    docker:
      - image: circleci/node:11
    working_directory: ~/app
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Test SCSS linting
          command: npm run stylelint
  deploy:
    docker:
      - image: circleci/node:11
    working_directory: ~/app
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Prune development dependencies
          command: npm prune --production
      - run:
          name: Remove source assets
          command: rm -rf src/assets
      - run:
          name: Deploy
          command: echo "Deploy step here"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
      - eslint:
          requires:
            - build
      - stylelint:
          requires:
            - build
      - deploy:
          requires:
            - unit-tests
            - eslint
            - stylelint
