name: Build and deploy test

on:
  push:
    branches:
      - feature/redesign

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: chrnorm/deployment-action@releases/v1
      name: Create GitHub deployment
      id: deployment
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_url: https://flamov.com/test
        environment: test

    - name: Get git hash
      id: hash
      run: echo "::set-output name=hash::$(git rev-parse --short=7 ${{ github.sha }})"

    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: Flamov
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: flamov/portfolio/portfolio
        tags: test

    - name: Deploy test image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          cd flamov-portfolio-compose
          cat ~/GH_TOKEN.txt | docker login docker.pkg.github.com -u Flamov -p --password-stdin
          docker-compose pull app-test
          docker-compose up --no-deps -d app-test

    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_url: https://flamov.com/test
        state: "success"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_url: https://flamov.com/test
        state: "failure"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
