name: Build and deploy test

on:
  push:
    branches:
      - feature/redesign

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get git hash
      id: hash
      run: echo "::set-output name=hash::$(git rev-parse --short=7 ${{ github.sha }})"
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: Flamov
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: flamov/portfolio/portfolio
        tags: test
    - name: Deploy test image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd flamov-portfolio-compose
          cat ~/GH_TOKEN.txt | docker login docker.pkg.github.com -u Flamov --password-stdin
          docker-compose pull app-test:test
          docker-compose up --no-deps -d app-test
