name: Deploy test

on:
  workflow_dispatch:
  push:
    branches:
      - feature/redesign

jobs:
  deploy-test:
    environment:
      name: test
      url: https://test.flamov.com

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get git hash
      id: hash
      run: echo "::set-output name=hash::$(git rev-parse --short=7 ${{ github.sha }})"

    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: Flamov
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: flamov/portfolio/portfolio
        tags: test

    - name: Deploy test image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          cd flamov-portfolio-compose
          echo ${{ secrets.PACKAGES_TOKEN }} | docker login docker.pkg.github.com -u Flamov --password-stdin
          docker-compose pull app-test
          docker-compose up --no-deps -d app-test
