name: Pull Request

on:
  pull_request:
    branches:
      - feature/redesign

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies and build assets
      run: npm ci --unsafe-perm && npm run assets:build
    - name: Test eslint
      run: npm run test:eslint:report
    - name: Test stylelint
      run: npm run test:stylelint
    - name: Test unit and integration
      run: npm run test:unit:coverage
